### ISSUE TITLE
Questions about BIP44

### ISSUE THREAD

**Issue by CryoCodex** [horizontalsystems/bitcoin-kit-ios#270]
Hello! I was wondering if you are able to have multiple accounts in the HDWallet BIP44 implementation (perhaps this question may sound dumb as I'm not 100% sure how things work)

root -> BIP44 -> coinType 0 -> account 0 -> chain 0 -> then N addresses here
  
That'd be to store bitcoin in account 0 right? is it possible to then derivate to account 1 in a way that

root -> BIP44 -> coinType 0 -> account 1 -> chain 0 -> again N addresses here

in the library so you would have 2 bitcoin accounts in the HDWallet? is there a way to just get the balances and transactions of account 0, then of account 1 individually I don't know if the question is being asked properly or if is not the way BIP44 is supposed to be intended just wondering if I wanted to have 2 bitcoin wallets I'd have to create another 12 word list mnemonic right? or there is a way to have 2 bitcoin wallets in the same HDWallet? Thanks in advance and I'm sorry if the question wasn't being asked properly, I've been learning a lot about crypto development thanks to all of you. Kudos and have a great day/night!

**Comment by ealymbaev** [comment]
Yes, you are right that BIP44 HDWallet can be used in this way, using several accounts.

But for now we have not implemented full support for multi-account wallet, because there are no many users who use this feature of BIP44. Implementing this would change the library API, and it will be implemented in future definitely.

The following features are implemented now:
- library scans all accounts as long as there are any transactions in them. It means that if user has ever used multi-account feature in his HD wallet - the library would be able to find all of his transactions.
- for generating new addresses for transactions library uses only first account (with index 0)

Please note that having multi-account support also requires complicated GUI in any app that would integrate this library.

**Comment by CryoCodex** [comment]
Oh alrighties, I was wondering about it since I had some doubts about the way it is intended to work, and yeah I totally agree about the GUI part! but is alright. the library has been of great help actually you guys are awesome!
