### ISSUE TITLE
Can bitcoinKit sign multisig transactions?

### ISSUE THREAD

**Issue by shyal** [horizontalsystems/bitcoin-kit-ios#514]
Hi,

Sorry i'm to new to this library & bitcoin to figure this out myself. Can BitcoinKit sign multisig transactions? If so, how?

Thanks.

**Comment by esengulov** [comment]
> Hi,
> 
> Sorry i'm to new to this library & bitcoin to figure this out myself. Can BitcoinKit sign multisig transactions? If so, how?
> 
> Thanks.

At the moment the bitcoin kit doesn't provide that capability. We are likely to extend it in the future to have that capability but it's not a priority at the moment.

**Comment by shyal** [comment]
How much work would it be? Happy to help.

**Comment by esengulov** [comment]
> How much work would it be? Happy to help.

Not a lot to be honest. Maybe a couple of weeks for a couple of us. It need to be researched, implemented and tested

**Comment by shyal** [comment]
happy to chat. i'm on google hangouts / slack / telegram etc. let me know what works for you

**Comment by esen** [comment]
Standard multisig transaction (P2MS) is not commonly used since P2SH became a standard ([more about this](https://learnmeabitcoin.com/guide/p2ms)). So, I personally don't think P2MS will be implemented. 

When it comes to multisig P2SH transactions, this kind of transactions, actually, can be built right now without any modifications to the kit. We have an interface for creating/detecting/spending any P2SH transactions. I believe it can be used to build multisig P2SH transactions. But keep in mind that you'll have to manage your partners' publicKeys/signatures yourself. This kit will only provide an interface to create/detect/spend the transaction.

We have [Atomic Swap Kit](https://github.com/horizontalsystems/atomic-swap-kit-ios) experimental project where we used that interface to build non-standard P2SH transactions. 
Particularly

- [This](https://github.com/horizontalsystems/atomic-swap-kit-ios/blob/update_pods/AtomicSwapBitcoinProvider/AtomicSwapBitcoinProvider/Provider/BitcoinSwapBlockchain.swift#L54) is how it creates a P2SH address and sends coins to it
- [This](https://github.com/horizontalsystems/atomic-swap-kit-ios/blob/update_pods/AtomicSwapBitcoinProvider/AtomicSwapBitcoinProvider/Provider/BitcoinSwapBlockchain.swift#L47) is how it detects that transaction on restore
- [This](https://github.com/horizontalsystems/atomic-swap-kit-ios/blob/update_pods/AtomicSwapBitcoinProvider/AtomicSwapBitcoinProvider/Provider/BitcoinSwapBlockchain.swift#L79) is how it spends from P2SH output.
